name: DeathToRaidable
version: ${project.version}${describe}
description: Factions addon which makes factions able to be raided when members die
author: meiskam

main: org.shininet.bukkit.deathtoraidable.DeathToRaidable
database: false

depend: [Factions]

commands:
  DeathToRaidable:
    description: View the DTR of a faction
    aliases: dtr

permissions:
  deathtoraidable.enable:
    description: DTR changes when player dies
    default: false