name: DeathToRaidable
version: ${project.version}${describe}
description: Factions addon which makes factions able to be raided when members die
author: meiskam

main: org.shininet.bukkit.deathtoraidable.DeathToRaidable
database: false